<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="App\**" />
    <Compile Remove="Shapes\**" />
    <EmbeddedResource Remove="App\**" />
    <EmbeddedResource Remove="Shapes\**" />
    <None Remove="App\**" />
    <None Remove="Shapes\**" />
  </ItemGroup>

</Project>
